import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import starlight from '@astrojs/starlight';
import starlightTypeDoc, { typeDocSidebarGroup } from 'starlight-typedoc';

import tailwind from '@astrojs/tailwind';

import sitemap from '@astrojs/sitemap';
const NETLIFY_PREVIEW_SITE =
	process.env.CONTEXT !== 'production' && process.env.DEPLOY_PRIME_URL;

const site = NETLIFY_PREVIEW_SITE || 'http://www.fabricjs.cc/';
// https://astro.build/config
export default defineConfig({
	// i18n: {
	// 	defaultLocale: 'zh-cn',
	// 	locales: ['zh-cn', 'en'],
	// 	routing: {
	// 		prefixDefaultLocale: false,
	// 	},
	// },
	site: site,
	integrations: [
		starlight({
			favicon: '/favicon.ico',
			title: 'FabricJS 文档和向导',
			social: {
				github: 'https://blog.csdn.net/codeex',
			},
			disable404Route: true,
			//defaultLocale: 'zh-cn',
			locales: {
				root: { label: '简体中文', lang: 'zh-CN' },
			},
			logo: {
				src: './src/assets/logo.svg',
				dark: './src/assets/logo-dark.svg',
				light: './src/assets/logo-light.svg',
				replacesTitle: true,
			},
			tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 4 },
			components: {
				Header: './src/components/Header/HeaderWithSearch.astro',
				PageTitle: './src/components/PageTitleDocs/PageTitle.astro',
				Pagination: './src/components/Pagination/index.astro',
			},
			sidebar: [
				{
					label: '参考文档',
					// Collapse the group and its autogenerated subgroups by default.
					collapsed: true,
					items: [
						{
							label: 'Getting started',
							translations: {
								'zh-CN': '新手启航',
							},
							badge: '入门',
							autogenerate: {
								directory: 'docs/Getting started',
								collapsed: false,
							},
						},
						'docs/configuring-defaults',
						'docs/configuring-controls',
						'docs/using-custom-properties',
						'docs',
						'docs/core-concepts',
						{
							collapsed: false,
							label: 'Understanding FabricJS',
							translations: {
								'zh-CN': '理解FabricJS',
							},
							autogenerate: { directory: 'docs/Understanding FabricJS' },
						},
						{
							collapsed: false,
							label: 'Upgrading',
							translations: {
								'zh-CN': '升级',
							},
							autogenerate: { directory: 'docs/Upgrading' },
						},
						{
							collapsed: true,
							label: 'Old docs',
							translations: {
								'zh-CN': '旧文档',
							},
							autogenerate: { directory: 'docs/Old docs' },
						},
					],
				},
				{
					label: 'Api',
					// Collapse the group and its autogenerated subgroups by default.
					collapsed: true,
					autogenerate: { directory: 'api' },
				},
			],
			customCss: [
				// Relative path to your custom CSS file
				'./src/layouts/colorvars.css',
				'./src/layouts/tailwind.css',
			],
			plugins: [
				// Generate the documentation.
				// starlightTypeDoc({
				//   entryPoints: ['./fabric.js/fabric.ts'],
				//   tsconfig: './fabric.js/typedoc.config.json',
				//   typeDoc: {
				//     plugin: ['typedoc-plugin-no-inherit'],
				//     readme: 'none',
				//     gitRemote: 'https://github.com/fabricjs/fabric.js/blob',
				//     entryFileName: 'index.md',
				//     includeVersion: true,
				//     sourceLinkExternal: true,
				//     sourceLinkTemplate: 'https://github.com/fabricjs/fabric.js/blob/{gitRevision}/{path}#L{line}',
				//   },
				// }),
			],
		}),
		react(),
		tailwind({
			nesting: true,
			applyBaseStyles: false,
		}),
		sitemap(),
	],
});
